### ISSUE TITLE
Create a sample app for React Native

### ISSUE THREAD

**Issue by fungc-io** [oursky/formx-sdk#3]
Create a sample app using FormX SDK to showcase the integration in React Native

The sample app should:
1. Home screen, 
    - A text field for "Extractor ID"
    - A text field for "Access Token"
    - A "Configure" button to save the settings
    - a button to open the camera view
2. The default camera view is opened, 
    - offline document is enabled
3. Show the picture captured
    - a button to "Start Extraction"
    - a button to "Retake"
4. Show loading screen during extraction
5. If extraction successful, show the extracted data printed in JSON
    - Show a button to "Restart", go back to home screen
7. if extraction failed, show alert
    - In the alert, Show button to "Restart", go back to home screen

**Comment by fungc-io** [comment]
Did that already in https://github.com/oursky/formx-sdk-react-native

**Comment by MarkRunWu** [comment]
@fungc-io current user may set required formx variables at environment file but not enter them in home screen. Would  we change back to two input fields ? Besides that others should be done.

**Comment by fungc-io** [comment]
Ok no worries, env variable will do too
